In [2]:
import numpy as np

#random.randn()
np.random.randn()

-0.966750968251307

In [3]:
#建立一了一個2 X 4的矩陣，並且隨機給它數值，最後將它加上1.920929這個數字

np.random.randn(2, 4) + 1.920929

array([[ 1.18049127, -0.01354447,  3.06617264,  3.04985183],
       [ 1.26906042,  0.55062918,  2.19944341,  2.69707171]])

In [5]:
# .random.randint()
# 4>的整數，大小為10

np.random.randint(4, size=10)

array([1, 1, 0, 0, 0, 2, 3, 2, 0, 2])

In [6]:
#產生大小為10，從4到小於10（9）的整數

np.random.randint(low=4,high=10,size=10)

array([8, 5, 6, 4, 7, 7, 7, 8, 9, 4])

In [6]:
#.mean() 建立一個5 X 4的隨機資料，並取平均值

x = np.random.randn(5, 4)
x

array([[-0.8195512 ,  0.27937994,  1.27931271, -0.14165034],
       [-1.11670904,  0.97610903,  0.53164771,  0.98075849],
       [-1.74532131,  0.21773677,  0.16691129,  0.503587  ],
       [-0.50914402, -1.02003606,  0.51915387,  0.52414817],
       [-0.42536413,  0.00532883, -0.10769916, -1.35268212]])

In [7]:
x.mean()

-0.06270417797946418

In [8]:
# .sum() 建立一個5 X 4的隨機資料，並取總和

x = np.random.randn(5, 4)
x.sum()

7.601581750444014

In [10]:
# .min()&.max() 建立一個5 X 4的隨機資料，並取最大跟最小值

xmin = np.random.randn(5, 4)
xmin.max()

xmax = np.random.randn(5, 4)
xmax.min()

-2.0399130090604167

In [11]:
# .cumsum() 回傳累積的數值：

'''
第一個index為2 = 2
第二個index為2+3 = 5
第三個index為2+3+4 = 9
第四個index為2+3+4+5 = 14
'''

x = np.array([[2,3,4], [5,6,7]])
np.cumsum(x)

array([ 2,  5,  9, 14, 20, 27], dtype=int32)

In [13]:
# .std() 接下來這個是標準差，統計領域的一定非常熟悉
# std = sqrt(mean(abs(x - x.mean())**2))

x = np.array([[1, 2], [3, 4]])
np.std(x)

1.118033988749895