In [11]:
#我們要找出和新數據附近的K個鄰居（資料），這些鄰居是哪一類（標籤）的它就是哪一類

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

#load_iris 要匯入鳶尾花的資料只需要使用datasets.load_iris()
iris = datasets.load_iris()

#定義特徵資料：
iris_data = iris.data

#可以印出前三筆資料：
iris_data[0:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [21]:
#定義標籤資料
iris_label = iris.target

#我們將資料分成兩份的程式碼：一部分是用來訓練電腦的(0.8)、一部份用來測試(0.2)
train_data , test_data , train_label , test_label = train_test_split(iris_data,iris_label,test_size=0.2)

In [22]:
#KNeighborsClassifier 要使用KNeighbors分類法，直接使用sklearn的KNeighborsClassifier()就可以了
knn = KNeighborsClassifier()
knn.fit(train_data,train_label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [23]:
#predict 預測我們剛剛切分出來的test_data資料
print(knn.predict(test_data))

[0 0 2 0 2 1 1 1 0 0 1 2 0 0 0 0 0 1 2 1 2 1 1 0 1 1 1 2 2 2]


In [24]:
#看一下正確答案是否跟預測一樣
print(test_label)

[0 0 2 0 2 1 1 1 0 0 1 2 0 0 0 0 0 1 2 1 2 1 1 0 1 1 1 2 2 1]
