In [3]:
import numpy as np
x = np.arange(10)

#save() 回Jupyter目錄看看是否有多出一個my_array.npy的檔案
np.save('my_array', x)

In [8]:
# load() 接下來我們將剛剛儲存的資料載入

np.load('my_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# savez() 我們可以儲存多個陣列在一個zip的檔案中，使用np.savez就可以

aData = [1,2,3,4,5,6]
bData = [7,8,9,10,11,12]

np.savez('my_archive.npz', a=aData, b=bData)

In [10]:
myArch = np.load('my_archive.npz')
myArch['b']

array([ 7,  8,  9, 10, 11, 12])

In [11]:
myArch['a']

array([1, 2, 3, 4, 5, 6])

In [21]:
'''
Jupyter內可以用!cat查看內容（跟在終端機的cat一樣）
cat不行就改用more或type
'''

#!more my_txt.txt
#!cat my_txt.txt
!type my_txt.txt

-0.8195512,0.27937994,1.27931271,-0.14165034
-1.11670904,0.97610903,0.53164771,0.98075849
-1.74532131,0.21773677,0.16691129,0.503587
-0.50914402,-1.02003606,0.51915387,0.52414817
-0.42536413,0.00532883,-0.10769916,-1.35268212


In [25]:
#load 在Numpy內會使用.loadtxt或特定的np.genfromtxt來讀取它
#我們使用np.loadtxt()，裡面的參數放入txt的檔案，delimiter=','則是設定分隔的符號

myArr = np.loadtxt('my_txt.txt', delimiter=',')
myArr = np.genfromtxt('my_txt.txt', delimiter=',')
myArr

array([[-0.8195512 ,  0.27937994,  1.27931271, -0.14165034],
       [-1.11670904,  0.97610903,  0.53164771,  0.98075849],
       [-1.74532131,  0.21773677,  0.16691129,  0.503587  ],
       [-0.50914402, -1.02003606,  0.51915387,  0.52414817],
       [-0.42536413,  0.00532883, -0.10769916, -1.35268212]])

In [26]:
#savetxt 要將資料反向存成另外一個txt檔案只需要

np.savetxt('txtfile.txt', myArr)