In [2]:
import numpy as np

data = np.array([[ 0.226, -0.23 , -0.86],
[ 0.5639, 0.2379, 0.904]])

np.array(data)

array([[ 0.226 , -0.23  , -0.86  ],
       [ 0.5639,  0.2379,  0.904 ]])

In [3]:
#Type provide 我們可以提供我們要的資料類型給它，只需要在括號內加上dtype=資料類型

data = np.array([1, 2, 3], dtype=complex)
np.array(data)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [0]:
data1 = [6, 7.5, 8, 0, 1]

np.array(data1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
np.array(data2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
#看資料(ndarray)有多少維
#記得要是ndarray的型態才可以用哦

arr2 = np.array(data2)
arr2.ndim

2

In [0]:
#看是幾乘幾的矩陣可以使用shape

arr2.shape

(2, 4)

In [0]:
#它和pandas相同也可以看資料類型

data.dtype

dtype('complex128')

In [0]:
#Creat data

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#Indexing

arr[5]

5

In [0]:
arr[5:8]

array([5, 6, 7])

In [0]:
#改變索引內的資料

arr[5:9] = 7
arr

array([0, 1, 2, 3, 4, 7, 7, 7, 7, 9])

In [0]:
#Slicing 只改變局部的資料，這就是所謂的Slicing

myarr = np.arange(10)
slice = myarr[5:8]
myarr[5:8] = 7
slice[1] = 87
myarr

array([ 0,  1,  2,  3,  4,  7, 87,  7,  8,  9])