In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,2,2])

a * b

array([2, 4, 6])

In [3]:
#廣播

c = np.array([1.0, 2.0, 3.0])
d = 2
c * d

array([2., 4., 6.])

In [13]:
#進階一點，這邊可能需要一點線性代數的概念

x = np.arange(4)

xx = x.reshape(4,1)

y = np.ones(5)


xx + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [16]:
#reshape() 簡單來說reshape()就是用來改變array的shape

s = np.arange(6)
s = s.reshape((3, 2))
s

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
#ndarray.T 這個是建立一個都是0的矩陣，矩陣形狀為 10 X 

x = np.zeros((10, 2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
#T這個是將x整個選轉變成2 X 10

y = x.T
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
x = np.array([[3,4],[5,6]])
x.T

array([[3, 5],
       [4, 6]])

In [23]:
#ndarray.base

y = np.array([1,2,3,4])
y.base is None

True

In [4]:
#xx是x來的，反之y不是xx來的

x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
(xx + y)

xx.base is x
xx.base is y

False